get http://localhost:8000/cats/-2
###
POST http://localhost:8000/cats
content-type: application/json

{
    "email":"bny@naver.com",
    "name":"cat",
    "password":"123"
}
###
POST http://localhost:8000/cats/login
content-type: application/json

{
    "email":"bny@naver.com",
    "password":"123"
}
###
GET http://localhost:8000/cats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJueUBuYXZlci5jb20iLCJzdWIiOiI2MTY3ZWNiZTA2ZjFjYWZhN2UwZDJiMTAiLCJpYXQiOjE2MzQ1MTk0NjcsImV4cCI6MTY2NjA3NzA2N30.kZxpaB4ceKE4c-sndpWg7C2h053tnsAD1U0kCGBn0AQ
###
